# Generated by Django 2.0.4 on 2018-04-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0009_auto_20180401_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
